version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel_app 
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:stable
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.2
    container_name: mysql_8_2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: dictionary
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      depends_on:
        - mysql
      ports:
        - "8080:80"
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
volumes:
  mysql_data:
  redis_data:
  ollama_data:
