<?php

namespace App\Contracts\Dictionary;

use App\Models\Languages\Language;
use App\Models\Dictionary\DictionaryElement;

/**
 * Interface for handling dictionary word translations.
 *
 * This interface defines the contract for services that manage
 * dictionary entries and their validation.
 */
interface WordTranslationServiceInterface
{
    /**
     * Validates the provided dictionary entry data.
     *
     * @param array $data The dictionary entry data to validate
     * @return bool Returns true if data is valid, false otherwise
     */
    public function isValidDictionaryElementData(array $data): bool;

    /**
     * Creates a new dictionary entry.
     *
     * @param array $data The dictionary entry data
     * @param Language $toLanguage The target language for the translation
     * @param Language $fromLanguage The source language being translated
     * @param bool $isAiGenerated Whether the entry was generated by AI (default: true)
     * @return DictionaryElement The created dictionary entry
     */
    public function createDictionaryEntry(
        array $data,
        Language $toLanguage,
        Language $fromLanguage,
        bool $isAiGenerated = true
    ): DictionaryElement;
}